name: Deploy EC2 

on: 
  push:
    branches:
      - ec2-sh-executable

jobs:
  deploy:
    name: Deploy to EC2 with executable SH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code and SSH into instance and run script
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          HOSTNAME: ${{ secrets.SERVER_HOST }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME}
          cd /apps/ec2-app
          ./deploy-be.sh



